### ISSUE TITLE
Does not work with `bcos` module out of the box

### ISSUE THREAD

**Issue by hanneskuettner** [sukrutrao/Model-Guidance#1]
This repo expects the local `bcos` package to be a modified version of the official `bcos` module.

If one tries to install the official `bcos` module we run into the problem that a package and a module with the same name result in import conflicts. 
But even after renaming the local `bcos` package to `bcos_local` and adjusting all the import statements accordingly it still expects a model that is not (yet?) available in the `bcos` repo.

https://github.com/sukrutrao/Model-Guidance/blob/06aed560fa8be59704620c1a0fab75c474e05d70/bcos/experiments/ImageNet/bcos_final/model.py#L5C40-L6C42

**Comment by sukrutrao** [comment]
Thank you for raising this issue -- the .gitignore was inadvertentently set to ignore the bcos.models directory, and has now been fixed. Please let us know if the issue still persists.

We also plan to update the official `bcos` module with the modifications soon and directly import the module in this repository.
